services:
  php:
    build:
      context: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
